### ISSUE TITLE
Mr. Rob Review

### ISSUE THREAD

**Issue by rwxrob** [troyjmiller/pro-project-summer-2016#1]
Good stuff! Just change the italics to regular font and get rid of any boilerplate italics that was left over from the fork. That italics was meant to be replaced with your own stuff.

**Comment by troyjmiller** [comment]
resolved

**Comment by troyjmiller** [comment]
#1 resolved

**Comment by troyjmiller** [comment]
#2

**Comment by troyjmiller** [comment]
resolved #1

**Comment by troyjmiller** [comment]
close #1
